name: matbert
emb_dim: 768
type:
  _target_: transformers.BertForMaskedLM.from_pretrained
  pretrained_model_name_or_path: pranav-s/MaterialsBERT
  output_hidden_states: True

tokenizer:
  _target_: transformers.BertTokenizer.from_pretrained
  pretrained_model_name_or_path: pranav-s/MaterialsBERT
